<?php

namespace App\Classes;

class Ticket
{

    public static $tickets = [
        'tickets' => [
            1 => ['id' => 1, 'name' => 'Brunch',    'price' => 12.2, 'date' => '2020/10/18', 'time' => '09:00', 'shortDesc' => 'Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion daikon amaranth tatsoi tomatillo melon azuki bean garlic.', 'largeDesc' => 'Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini. Turnip greens yarrow ricebean rutabaga endive cauliflower sea lettuce kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter purslane kale. Celery potato scallion desert raisin horseradish spinach carrot soko. Lotus root water spinach fennel kombu maize bamboo shoot green bean swiss chard seakale pumpkin onion chickpea gram corn pea. Brussels sprout coriander water chestnut gourd swiss chard wakame kohlrabi beetroot carrot watercress. Corn amaranth salsify bunya nuts nori azuki bean chickweed potato bell pepper artichoke.'],
            2 => ['id' => 2, 'name' => 'Lunch',     'price' => 22.2, 'date' => '2020/10/19', 'time' => '14:00', 'shortDesc' => 'Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery. Bunya nuts black-eyed pea prairie turnip leek lentil turnip greens parsnip', 'largeDesc' => 'Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard. Pea horseradish azuki bean lettuce avocado asparagus okra. Kohlrabi radish okra azuki bean corn fava bean mustard tigernut jï¿½cama green bean celtuce collard greens avocado quandong fennel gumbo black-eyed pea. Grape silver beet watercress potato tigernut corn groundnut. Chickweed okra pea winter purslane coriander yarrow sweet pepper radish garlic brussels sprout groundnut summer purslane earthnut pea tomato spring onion azuki bean gourd. Gumbo kakadu plum komatsuna black-eyed pea green bean zucchini gourd winter purslane silver beet rock melon radish asparagus spinach.'],
            3 => ['id' => 3, 'name' => 'Dinner',    'price' => 18.2, 'date' => '2020/10/20', 'time' => '19:00', 'shortDesc' => 'Bacon ipsum dolor amet pastrami burgdoggen turducken biltong. Bacon corned beef flank, chuck drumstick rump kielbasa frankfurter doner brisket tenderloin chislic leberkas short ribs pork chop.', 'largeDesc' => 'Kielbasa chislic porchetta meatball bacon ball tip, ham hock pork belly chuck doner short ribs capicola beef. Fatback chuck biltong jowl cow turducken ham. Tri-tip pastrami flank chicken chuck boudin strip steak pork loin cow kielbasa jerky beef ribs brisket spare ribs tongue. Capicola cow strip steak, tail shoulder chislic tri-tip picanha meatloaf alcatra t-bone spare ribs kevin chicken salami. Corned beef tail pork chop salami burgdoggen beef beef ribs tenderloin flank.'],
            4 => ['id' => 4, 'name' => 'Breakfast', 'price' => 7.2,  'date' => '2020/10/21', 'time' => '21:00', 'shortDesc' => 'Ground round flank prosciutto pastrami pork belly frankfurter. Meatball brisket burgdoggen, strip steak leberkas venison shoulder turducken biltong jowl ham pork beef ribs ball tip tongue.', 'largeDesc' => 'Hamburger shoulder boudin, leberkas jerky strip steak sirloin jowl flank kevin venison ham hock buffalo tail meatball. Short ribs flank biltong, pork loin rump porchetta filet mignon drumstick kevin pastrami. Shoulder strip steak jerky, flank kevin picanha ham hock frankfurter bresaola shankle cow. Jerky landjaeger ball tip, jowl brisket pork belly leberkas prosciutto kevin. Cow tenderloin tongue capicola chislic tail jowl venison shoulder short ribs strip steak kielbasa. Fatback meatball shank short loin andouille porchetta beef ribs burgdoggen sausage kielbasa kevin bacon pork loin. Filet mignon tongue spare ribs burgdoggen boudin, ham hock bresaola shoulder. Cupim pork tri-tip ground round filet mignon, beef pork belly andouille rump prosciutto bacon sausage chuck jowl short loin.'],
        ],
    ];
}
